services:
  kinematics:
    container_name: kinematics
    build:
      context: ./kinematics

    volumes:
    - ./kinematics:/home/user/src
    stdin_open: true
    tty: true

  robot_control:
    container_name: robot_control
    build:
      context: ./robot_control

    volumes:
    - ./robot_control:/home/user/src
    stdin_open: true
    tty: true
